var MeteorPlayer, mtrPlayer, myCL, networkStates, readyStates,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

networkStates = {
  0: 'empty',
  1: 'idle',
  2: 'loading',
  3: 'no source'
};

readyStates = {
  0: 'nothing',
  1: 'metadata',
  2: 'current',
  3: 'future',
  4: 'enough'
};

myCL = function(l) {
  return _.each(l, function(msg) {
    return console.log(msg);
  });
};

this.mtrPlayer = mtrPlayer = new (MeteorPlayer = (function() {
  MeteorPlayer.prototype.readyState = null;

  MeteorPlayer.prototype.networkState = null;

  MeteorPlayer.prototype.audioTag = function() {
    return $('#player')[0];
  };

  function MeteorPlayer() {
    this.checkStatus = bind(this.checkStatus, this);
    this.play = bind(this.play, this);
    Meteor.startup(function() {
      return mtrPlayer.setChannel(location.hash.slice(1));
    });
    Meteor.setInterval(function() {
      if (mtrPlayer.audioTag()) {
        return mtrPlayer.checkStatus();
      }
    }, 7000);
  }

  MeteorPlayer.prototype.play = function() {
    var ref;
    console.log('trying to .play()');
    return (ref = this.audioTag()) != null ? ref.play() : void 0;
  };

  MeteorPlayer.prototype.setChannel = function(channel) {
    this.readyState = this.networkState = null;
    Session.set('channel', '');
    Meteor.setTimeout((function() {
      return Session.set('channel', channel);
    }), 200);
    location.href = '#' + channel;
    return document.title = channel + ' | radio.meteor.com';
  };

  MeteorPlayer.prototype.checkStatus = function() {
    var newNetworkState, newReadyState;
    newNetworkState = this.audioTag().networkState;
    newReadyState = this.audioTag().readyState;
    this.audioTag().volume = 1;
    this.play();
    myCL(['checkStatus net', newNetworkState, this.networkState, 'ready', newReadyState, this.readyState, 'currentTime', this.audioTag().duration]);
    if ((this.readyState != null) && newReadyState === this.readyState && [0, 1].indexOf(newReadyState) > -1 && newNetworkState !== 2) {
      console.log('Restart channel');
      this.readyState = this.networkState = null;
      return this.setChannel(Session.get('channel'));
    } else {
      if (this.audioTag().currentTime) {
        $('#currentTime')[0].innerHTML = moment().subtract('seconds', Math.round(this.audioTag().currentTime)).fromNow(true);
      }
      if (newReadyState) {
        $('#readyState')[0].innerHTML = readyStates[newReadyState];
      }
      if (newNetworkState) {
        $('#networkState')[0].innerHTML = networkStates[newNetworkState];
      }
      this.readyState = newReadyState;
      return this.networkState = newNetworkState;
    }
  };

  return MeteorPlayer;

})());

// ---
// generated by coffee-script 1.9.2
